[0m[1mInitializing modules...[0m
- local_application_insights in
- local_container_registry in
- local_key_vault in ../../../key-vault
- local_key_vault.kv_pe in ../../../private-endpoint
- local_mlw in ../../machine-learning-workspace
- local_mlw.mlw_pe in ../../../private-endpoint
- local_rg in ../../../resource-group
- local_snet_default in ../../../subnet
- local_storage_account in ../../../storage-account
- local_storage_account.st_pe_blob in ../../../private-endpoint
- local_storage_account.st_pe_dfs in ../../../private-endpoint
- local_storage_account.st_pe_file in ../../../private-endpoint
- local_vnet in ../../../virtual-network
- machine_learning_compute_cluster in ..
[31mâ•·[0m[0m
[31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mUnreadable module directory[0m
[31mâ”‚[0m [0m
[31mâ”‚[0m [0m[0mUnable to evaluate directory symlink: lstat ../../../application-insights:
[31mâ”‚[0m [0mno such file or directory
[31mâ•µ[0m[0m
[31mâ•·[0m[0m
[31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mUnreadable module directory[0m
[31mâ”‚[0m [0m
[31mâ”‚[0m [0m[0mThe directory  could not be read for module "local_application_insights" at
[31mâ”‚[0m [0mmachine_learning_compute_cluster.tf:64.
[31mâ•µ[0m[0m
[31mâ•·[0m[0m
[31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mUnreadable module directory[0m
[31mâ”‚[0m [0m
[31mâ”‚[0m [0m[0mUnable to evaluate directory symlink: lstat ../../../container-registry: no
[31mâ”‚[0m [0msuch file or directory
[31mâ•µ[0m[0m
[31mâ•·[0m[0m
[31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mUnreadable module directory[0m
[31mâ”‚[0m [0m
[31mâ”‚[0m [0m[0mThe directory  could not be read for module "local_container_registry" at
[31mâ”‚[0m [0mmachine_learning_compute_cluster.tf:71.
[31mâ•µ[0m[0m
Error: 'terraform init -backend=false' failed in ./wts-azure-modules/azure/machine-learning/machine-learning-compute-cluster/test
